<?php


return [
    "Baringo" => ["Baringo Central", "Baringo North", "Baringo South", "Eldama Ravine", "Mogotio", "Tiaty"],
    "Bomet" => ["Bomet Central", "Bomet East", "Chepalungu", "Konoin", "Sotik"],
    "Bungoma" => ["Bumula", "Kabuchai", "Kanduyi", "Kimilili", "Mt. Elgon", "Sirisia", "Tongaren", "Webuye East", "Webuye West"],
    "Busia" => ["Bunyala", "Butula", "Matayos", "Nambale", "Samia", "Teso North", "Teso South"],
    "Elgeyo Marakwet" => ["Keiyo East", "Keiyo South", "Marakwet East", "Marakwet West"],
    "Embu" => ["Embu East", "Embu North", "Embu West", "Mbeere North", "Mbeere South"],
    "Garissa" => ["Balambala", "Dadaab", "Fafi", "Garissa", "Hulugho", "Ijara", "Lagdera"],
    "Homa Bay" => ["Homa Bay Town", "Kabondo Kasipul", "Karachuonyo", "Kasipul", "Mbita", "Ndhiwa", "Rangwe", "Suba"],
    "Isiolo" => ["Galbatulla", "Isiolo", "Merti"],
    "Kajiado" => ["Kajiado Central", "Kajiado East", "Kajiado North", "Kajiado South", "Kajiado West", "Mashuuru", "Oloililai"],
   	"Kakamega"=>	["Butere", "Ikolomani", "Khwisero", "Likuyani", "Lugari", "Lurambi", "Malava", "Matungu", "Mumias", "Mumias East", "Navakholo", "Shinyalu"],
    "Kericho"=>	["Ainamoi", "Belgut", "Bureti", "Kipkelion East", "Kipkelion West", "Soin/Sigowet"],
    "Kiambu"=>	["Gatundu North", "Gatundu South", "Githunguri", "Juja", "Kabete", "Kiambaa", "Kiambu Town", "Kikuyu", "Lari", "Limuru", "Ruiru", "Thika town"],
    "Kilifi"=>	["Ganze", "Kaloleni", "Kilifi North", "Kilifi South", "Magarini", "Malindi", "Rabai"],
    "Kirinyaga"=>	["Kirinyaga Central", "Kirinyaga East", "Kirinyaga West", "Mwea East", "Mwea West"],
    "Kisii"=>	["Bobasi", "Bomachoge Borabu", "Bomachoge Chache", "Bonchari", "Kitutu Chache North", "Kitutu Chache South", "Nyaribari Chache", "Nyaribari Masaba", "South Mugirango"],
    "Kisumu"=>	["Kisumu Central", "Kisumu East", "Kisumu West", "Muhoroni", "Nyakach", "Nyando", "Seme"],
  	"Kitui" =>	["Kitui Central", "Kitui East", "Kitui Rural", "Kitui South", "Kitui West", "Mwingi Central", "Mwingi North", "Mwingi West"],
	"Kwale"=>	["Kinango", "Lunga Lunga", "Matuga", "Msambweni"],
	"Laikipia"=> [ "Kirima", "Laikipia Central", "Laikipia East", "Laikipia North", "Laikipia West", "Nyahururu"],
	"Lamu"=>	["Lamu East", "Lamu West"],
	"Machakos"=>	["Kangundo", "Kathiani", "Machakos Town", "Masinga", "Matungulu", "Mavoko", "Mwala", "Yatta"],
    "Makueni" => ["Kaiti", "Kibwezi East", "Kibwezi West", "Kilome", "Makueni", "Mbooni"],
    "Mandera" => ["Banisa", "Kutulo", "Lafey", "Mandera Central", "Mandera East", "Mandera North", "Mandera West"],
    "Marsabit" => ["Laisamis", "Moyale", "North Horr", "Saku"],
    "Meru" => ["Buuri", "Central Imenti", "Igembe Central", "Igembe North", "Igembe South", "North Imenti", "South Imenti", "Tigania East", "Tigania West"],
    "Migori" => ["Awendo", "Kuria East", "Kuria West", "Mabera", "Ntimaru", "Nyatike", "Rongo", "Suna East", "Suna West", "Uriri"],
    "Mombasa" => ["Changamwe", "Jomvu", "Kisauni", "Likoni", "Mvita", "Nyali"],
    "Murang’a" => ["Gatanga", "Kahuro", "Kigumo", "Kiharu", "Kandara", "Kangema", "Mathioya", "Murang’a South"],
    "Nairobi" => ["Dagoretti", "Embakasi", "Kamukunji", "Kasarani", "Kibra", "Lang'ata", "Makadara", "Mathare", "Njiru", "Starehe", "Westlands"],
    "Nakuru" => ["Bahati", "Gilgil", "Kuresoi North", "Kuresoi South", "Molo", "Naivasha", "Nakuru Town East", "Nakuru Town West", "Njoro", "Rongai", "Subukia"],
    "Nandi" => ["Aldai", "Chesumei", "Emgwen", "Mosop", "Nandi Hills", "Tinderet"],
    "Narok" => ["Narok East", "Narok North", "Narok South", "Narok West", "Transmara East", "Transmara West"],
    "Nyamira" => ["Borabu", "Manga", "Masaba North", "Nyamira North", "Nyamira South"],
    "Nyandarua" => ["Kinangop", "Kipipiri", "Ndaragwa", "Ol-Jorok", "Ol-Kalou"],
    "Nyeri" => ["Kieni East", "Kieni West", "Mathira East", "Mathira West", "Mukurweini", "Nyeri Town", "Othaya", "Tetu"],
    "Samburu" => ["Samburu East", "Samburu North", "Samburu West"],
    "Siaya" => ["Alego Usonga", "Bondo", "Gem", "Rarieda", "Ugenya", "Ugunja"],
    "Taita Taveta" => ["Mwatate", "Taveta", "Voi", "Wundanyi"],
    "Tana River" => ["Bura", "Galole", "Garsen"],
    "Tharaka Nithi" => ["Maara", "Meru South", "Tharaka North", "Tharaka South"],
    "Trans Nzoia" => ["Cherengany", "Endebess", "Kiminini", "Kwanza", "Saboti"],
  
];
